# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SFLqX_FUH9qySDuhPupdKyrIT-eXzGjJ
"""

# ecuaciones diferenciales para turistas
import numpy as np

#pendulo simple 

gravedad = 9.2
longitudCuerda = 2
resitenciaAire = 0.1

# ecuacion diferencial
def aceleracionAng(tetha , velAngular):  # tetha es el angulo
  return resistenciaAire* velAngular -(gravedad/longitudCuerda)* np.sin(tetha)

#solucion de la ec diferencial

def tetha(ang):
  angulo = theta   # toma condiciones iniciales
  velAngular = thetaPunto 
  
  
  muestra = 0.01 # cambio en el tiempo de como se tomaran muestras corresponde a un delta t
  for tiempo in range(0,ang,muestra):
    angulo += velAngular * muestra

    aceleracionAng(angulo , velAngular) # tomar la aceleracion
    velAngular += aceleracionAngular * muestra
    print(angulo)
  return angulo 



# condiciones iniciales de la edo
theta = np.pi / 3 # 60 grados
thetaPunto = 0    # sin vel angular inicial 

tetha(int(3))