# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SYsdck3x9LzTEOalfC1xB9PY2D5BSxrW
"""

# metodo isoclinas

from pylab import *
diffeEq = Y**2 - X
xmax = 4.0; xmin = -xmax
ymax = 4.0 ; ymin = -ymax
puntos = 20

x = linspace(xmin, xmax, puntos) ; y = linspace(ymin, ymax, puntos)
X, Y = meshgrid(x, y)
# deg = arctan(diffeEq)
#QP = quiver(X,Y,cos(deg),sin(deg))

QP = quiver(X,Y,diffeEq,-diffeEq)
show()



# quiver doc : https://matplotlib.org/3.1.3/api/_as_gen/matplotlib.pyplot.quiver.html

