# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cAXuQJoBAdF4Gj50Op933EEtzPzUHNf3
"""

# espiral logaritmica
import matplotlib.pyplot as plt
import math


k = 1 # step 
# Assign theta, x, and y below. Do not change these variable names. 

a = 0.5 ;b = 0.5

X = [] ; Y = []
for angle in range(0,360,k):
  X.append(a*(b**angle)* math.cos(angle) )
  Y.append(a*(b**angle)* math.sin(angle) )

 
print(X)



#Graphics
plt.plot(X,Y)
plt.axis("equal")
plt.grid()
plt.show()

# espiral logaritmica
import matplotlib.pyplot as plt
import math


k = 1 # step 
# Assign theta, x, and y below. Do not change these variable names. 

a = 0.5 ;b = 0.5

X = [] ; Y = []

angle= 0 ; bLim = 360
thetas = []
step = 0.05
i = 0
while i <= bLim/ step:
  thetas.append(round(float(angle) , 2  ))
  angle += step
  i += 1

print(thetas)

for i in thetas:
  c = a*(b**i)
  X.append( c*  math.cos(i) )
  Y.append( c*  math.sin(i) )


 
print(X)



#Graphics
plt.plot(X,Y)
plt.axis("equal")
plt.grid()
plt.show()