# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TnKqmEJ2yNPHmjUWfaaZKCO8cU8vE0vB
"""

# mapalogistico

import matplotlib.pyplot as plt
import numpy as np


r = 2.6 # taza de crecimiento 
xn = 0.4  #porcentaje del maximo

i = 0

XN = [] ; XN1 = []  #xn1  taza crecimiento 
while i <= 100 :
  xn1 = (r*xn)*(1- xn) 
  
  XN.append(xn) ; XN1.append(xn1)
  xn = xn1
  i += 1

print(XN)
plt.plot(XN,XN1)
plt.show()


plt.plot(XN1)
plt.show()

import matplotlib.pyplot as plt
from matplotlib.widgets import Slider

x = list(range(0,11))
y = [10]*11

fig , az = plt.subplots()
plt.subplots_adjust(left=0.1, bottom=0.35)
p = plt.plot(x,y)

axSlider = plt.axes([0.1,0.2,0.8,0.05])
slider1 = Slider(axSlider, 'Slider 1',valmin=0,valmax=100)

def valorUpdate(val):
  yValor = slider1.val
  p.set_ydata(yValor)
  plt.draw()

slider1.on_changed(valorUpdate)



# mapalogistico

import matplotlib.pyplot as plt
import numpy as np


r = np.linspace(0,5 ,10 ) # taza de crecimiento 
xn = 0.4  #porcentaje del maximo

XN = [] ; XN1 = []  #xn1  taza crecimiento 
while i <= 100 :
  for i in range(len(r)):
    xn1 = (r[i]*xn)*(1- xn) 
  
  XN.append(xn) ; XN1.append(xn1)
  xn = xn1
  i += 1

i = 0

XN = [] ; XN1 = []  #xn1  taza crecimiento 

 

print(XN)
plt.plot(XN,XN1)
plt.show()


plt.plot(XN1)
plt.show()