# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fc-OeWWUNdOTWxuzd2PRadxlH5zG-rJt
"""

# 1. Compute the values of cos x and sin x for x = 0, p/6, p/4, p/3, and p/2.

import math

# pi rad   180 grad
# b         a



step = math.pi/8
xValue = 0

def radToDeg(rad):
  return (rad * 180 ) / math.pi



while xValue < math.pi * 2:
  
  cos = math.cos(xValue)
  sin = math.sin(xValue)
  
  print(f"rad = {xValue} , deg = {radToDeg(xValue)}  |Cos({xValue}) = {cos}     |     Sin({xValue}) = {sin} " )
  xValue += step


# https://sites.google.com/site/precalculojaimevera/1--funciones/funciones-trigonometricas

